### ISSUE TITLE
PUT url out of sync with blog post code

### ISSUE THREAD

**Issue by alansegar** [oktadeveloper/okta-spring-boot-react-crud-example#22]
Thanks for creating the blog post related to this repo - very helpful. I've just followed the guide https://developer.okta.com/blog/2018/07/19/simple-crud-react-and-spring-boot and found that GitHub is OK (as in the PUT fix is there) but the code samples in the text of the webpage are out of date compared to the latest in GitHub and don't contain the PUT fix. 
Webpage has     
```
await fetch('/api/group', {
      method: (item.id) ? 'PUT' : 'POST', 
```
in GroupEdit.js (handleSubmit function) which only works for POST / create, not PUT / edit.  
If the webpage were updated to match github then people can follow the guide without having to diff with GitHub to find the fix. The modified code in GitHub is `await fetch('/api/group' + (item.id ? '/' + item.id : '') , {`

**Comment by mraible** [comment]
Thanks for the heads up @alansegar! If you create a pull request to fix it on our blog, I'll send you a t-shirt. 🙂

Here's the file you'll need to fix: 

https://github.com/oktadeveloper/okta-blog/blob/main/_source/_posts/2018-07-19-simple-crud-react-and-spring-boot.md

We have [how to contribute docs](https://github.com/oktadeveloper/okta-blog#how-to-create-a-pull-request) in the repo's README.

**Comment by alansegar** [comment]
@mraible I've created the pull request at https://github.com/oktadeveloper/okta-blog/pull/471 and followed the how to contribute docs to use docker to check that it renders the updated blog post OK locally.

**Comment by mraible** [comment]
Thanks, @alansegar! Please send your address and t-shirt size to matt.raible@okta.com and I'll get one shipped out to you.
