### ISSUE TITLE
Add table name to "User" model

### ISSUE THREAD

**Issue by minamo7sen** [oktadeveloper/okta-spring-boot-react-crud-example#49]
Hello,

A small suggestion;

In H2 database version 2.x, "User" is a [reserved word](http://www.h2database.com/html/advanced.html#keywords).

The code could work with H2 version 2.x without errors if the table is renamed to "users" for example. i.e.: adding the following annotation to the "User" class.
```
@Table(name = "users")
```

Thank you.

**Comment by mraible** [comment]
Thanks for this @minamo7sen! Can I sent you a t-shirt for your efforts? If so, please send an email to matt.raible@okta.com with your size and address.
