### ISSUE TITLE
Authentication Issue with running app

### ISSUE THREAD

**Issue by ccaspanello** [oktadeveloper/okta-spring-boot-react-crud-example#7]
After updating the client-id, client-secret, and issuer-url I get the following error.

Identity Provider: Unknown
Error Code: invalid_request
Description: The 'redirect_uri' parameter must be an absolute URI that is whitelisted in the client app settings.

I followed the instructions in the related blog post to create the Web Application in Okta.  Can you please give me any other debugging tips?  I have this gut feeling I'm missing something in the Okta configuration.

Note:  If I run the app without modifying the application.yml file I don't get the above error; but I am obviously not able to log into my Application since it is pointing to your Okta application.

**Comment by mraible** [comment]
Make sure your app has the following redirect URI:

http://localhost:8080/login/oauth2/code/okta

You should be able to see the redirect URI it’s trying to use as a parameter in the URL.
